### ISSUE TITLE
ReferenceError: option is not defined in textSizes.js

### ISSUE THREAD

**Issue by rainypixels** [cwsdigital/tailwind-utopia#4]
This happens when I save `tailwind.config.js`:

```
Found Tailwind CSS config file: [...]/code/tailwind.config.js
Loaded postcss v8.3.5: [...]/code/node_modules/postcss
Loaded tailwindcss v2.2.4: [...]/code/node_modules/tailwindcss
[Error - 11:17:32 AM] Tailwind CSS: option is not defined
ReferenceError: option is not defined
    at [...]/code/node_modules/tailwind-utopia/lib/textSizes.js:84:56
    at Array.map (<anonymous>)
    at module.exports ([...]/code/node_modules/tailwind-utopia/lib/textSizes.js:77:34)
    at Object.handler (/Users/n/Development/work/rainypixels_com/v5/code/node_modules/tailwind-utopia/index.js:98:9)
    at Object.handler (/Users/n/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.12/dist/server/tailwindServer.js:56:348270)
    at Object.handler (/Users/n/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.12/dist/server/tailwindServer.js:56:348270)
    at Object.handler (/Users/n/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.12/dist/server/tailwindServer.js:56:348270)
    at Object.handler (/Users/n/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.12/dist/server/tailwindServer.js:56:348270)
    at Object.handler (/Users/n/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.12/dist/server/tailwindServer.js:56:348270)
    at Object.handler (/Users/n/.vscode/extensions/bradlc.vscode-tailwindcss-0.6.12/dist/server/tailwindServer.js:56:348270)
```

[This is the line](https://github.com/cwsdigital/tailwind-utopia/blob/1fc07fc37db8d48e3072d9663314f1f5b4deca99/lib/textSizes.js#L84). I believe it needs to be `options.baseTextSize`? Same goes for [this line](https://github.com/cwsdigital/tailwind-utopia/blob/1fc07fc37db8d48e3072d9663314f1f5b4deca99/lib/textSizes.js#L31).

**Comment by chrispymm** [comment]
Fixed in tag v1.0.3
